image: registry.gitlab.com/gitlab-org/terraform-images/releases/1.4:v1.0.0

stages:
  - validate
  - deploy

variables:
  TERRAFORM_MODULE_SYSTEM: kypo
  TERRAFORM_MODULE_DIR: ${CI_PROJECT_DIR}
  TERRAFORM_MODULE_VERSION: ${CI_COMMIT_TAG}

fmt:
  stage: validate
  variables:
    TF_ROOT: $TERRAFORM_MODULE_DIR
  script:
    - gitlab-terraform fmt

deploy:
  stage: deploy
  script:
    - TERRAFORM_MODULE_NAME=$(echo "${CI_PROJECT_NAME}" | sed "s|^terraform-${TERRAFORM_MODULE_SYSTEM}-||" | tr " _" -)  # module-name must not have spaces or underscores, so translate them to hyphens
    # Builds the Terraform module artifact: a gzipped tar archive with the contents from `$TERRAFORM_MODULE_DIR` without a `.git` directory.
    - tar -vczf /tmp/${TERRAFORM_MODULE_NAME}-${TERRAFORM_MODULE_SYSTEM}-${TERRAFORM_MODULE_VERSION}.tgz -C ${TERRAFORM_MODULE_DIR} --exclude=./.git .
    # Uploads the Terraform module artifact to the GitLab Terraform Module Registry, see
    # docs/user/packages/terraform_module_registry/index.html#publish-a-terraform-module
    - 'curl --fail-with-body --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}"
         --upload-file /tmp/${TERRAFORM_MODULE_NAME}-${TERRAFORM_MODULE_SYSTEM}-${TERRAFORM_MODULE_VERSION}.tgz
         ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/terraform/modules/${TERRAFORM_MODULE_NAME}/${TERRAFORM_MODULE_SYSTEM}/${TERRAFORM_MODULE_VERSION}/file'
  rules:
    - if: $CI_COMMIT_TAG
