name: Terraform build/destroy template

on:
  workflow_call

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  TF_VAR_KYPO_ENDPOINT: "https://images.crp.kypo.muni.cz"
  TF_VAR_CI_PROJECT_URL: ${{ github.event.repository.html_url }}
  TF_VAR_CI_COMMIT_SHORT_SHA: ${{ github.sha }}
  
  CRCZP_ENDPOINT: "https://images.crp.kypo.muni.cz"
  CRCZP_USERNAME: ${{ secrets.CRCZP_USERNAME }}
  CRCZP_PASSWORD: ${{ secrets.CRCZP_PASSWORD }}


jobs:
  terraform-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform
        run: terraform init

      - name: Vaidate Terraform
        run: terraform validate
      
      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve
      
      - name: Show an output
        run: tofu output pool_url
        #todo make some action message
      
      - name: Destroy Tofu
        run: terraform destroy -auto-approve
      
