name: Terraform build/destroy template

# on:
#   workflow_call
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  TF_VAR_KYPO_ENDPOINT: "https://images.crp.kypo.muni.cz"
  TF_VAR_CI_PROJECT_URL: ${{ github.event.repository.html_url }}
  TF_VAR_CI_COMMIT_SHORT_SHA: ${{ github.sha }}
  
  CRCZP_ENDPOINT: "https://images.crp.kypo.muni.cz"
  CRCZP_USERNAME: ${{ secrets.CRCZP_USERNAME }}
  CRCZP_PASSWORD: ${{ secrets.CRCZP_PASSWORD }}


jobs:
  tofu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Tofu
        uses: opentofu/setup-opentofu@v1

      - name: Init Tofu
        run: tofu init

      - name: Vaidate Tofu
        run: tofu validate
      
      - name: Plan Tofu
        run: tofu plan

      - name: Apply Tofu
        run: tofu apply -auto-approve
      
      - name: Show an output
        run: |
          tofu output pool_url
          echo "::notice title=Tofu output (Pool URL)::$(tofu output pool_url | tr '\n' ' ')"
      
      - name: Destroy Tofu
        run: tofu destroy -auto-approve
      
