name: Terraform destroy template

on:
  workflow_call

jobs:
  
  terraform-destroy:
    runs-on: ubuntu-latest
    # needs: terraform-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Tofu
        uses: hashicorp/setup-terraform@v3
      
      - name: Destroy Tofu
        run: terraform destroy -auto-approve
      
      # - name: Delete Terraform State
      #   run: |
      #     curl --header "Private-Token:${{ secrets.TF_PASSWORD }}" --request DELETE "${{ github.api_url }}/projects/${{ github.repository }}/terraform/state/${{ github.ref_name }}" || true
